### ISSUE TITLE
Objects are being stored as strings.

### ISSUE THREAD

**Issue by BenMorganIO** [andersondias/sidekiq_mailer#18]
I have several objects that I pass to my emails.

What's happening is that I can't seem to access them anymore. The error that appears is along the lines of:

```
undefined method `first_name' for "#<User:0x007ff18a8a5f38>":String
```

Is there a way to make Sidekiq Mailer object safe?

**Comment by andersondias** [comment]
Hello @BenMorganIO, I've created a wiki page explaining how to migrate mailers to use Sidekiq::Mailer:

https://github.com/andersondias/sidekiq_mailer/wiki/Migrating-to-Sidekiq::Mailer

If you have any question about it after reading this page, please feel free to open another issue.

Best.
