### ISSUE TITLE
NameError - uninitialized class variable @@excluded_environments in Sidekiq::Mailer:

### ISSUE THREAD

**Issue by pmontrasio** [andersondias/sidekiq_mailer#2]
I didn't define any excluded_environments and it seems that the gem can't cope with that.
I added :test in an initializer as per the README and it works.

**Comment by andersondias** [comment]
There is a new version of the gem, can you try it? tks

**Comment by barmstrong** [comment]
This seems to still be broken in version 0.0.6.  Tried with latest commit also b27c091beaebd8636e84908d5d9afaebc3db8eb0.

I tried switching to this pull request: https://github.com/andersondias/sidekiq_mailer/pull/3

``` ruby
gem 'sidekiq_mailer', git: 'git://github.com/tubaxenor/sidekiq_mailer.git', ref: 'cc8f6d0cf941d0a43cc694e6d2e20e25081e2d03'
```

And that fixed it.  Maybe this should be merged in and version bump to 0.0.7?  Thanks for taking a look!

**Comment by cheshire137** [comment]
This is still a problem in 0.0.6.

**Comment by funkenstrahlen** [comment]
Same error here.

**Comment by tamvm** [comment]
Why does the author not check this issue in Rails 4?

**Comment by andersondias** [comment]
@tam-vo @i42n @moneypenny @barmstrong @pmontrasio this error was fixed on 0.0.8 release.

**Comment by dapi** [comment]
Still have such problem with rails 4.1

**Comment by tamvm** [comment]
It may cause by serialization in sidekiq. I just found a quick solution for this issue: pass primary value for delay method instead object or anything.
